# Generated by Django 2.2.1 on 2020-06-15 01:12

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='ip/domain to block')),
            ],
            options={
                'verbose_name': 'blocked domain',
                'verbose_name_plural': 'blocked domains',
            },
        ),
        migrations.CreateModel(
            name='BlockRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('domain', models.CharField(max_length=100, verbose_name='ip/domain to block')),
                ('user_email', models.EmailField(max_length=254, verbose_name="user's email")),
                ('user_ip', models.GenericIPAddressField()),
                ('description', models.TextField(verbose_name='reason to block')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'APPROVED'), (2, 'REFUSED')], default=0, verbose_name='request status')),
            ],
            options={
                'verbose_name': 'block request',
                'verbose_name_plural': 'blocked domains',
            },
        ),
    ]
